### ISSUE TITLE
It takes a lot of time to install tested modules when, may be, it is not required.

### ISSUE THREAD

**Issue by rchamorro** [gisce/destral#108]
I am not sure if this is possible, but each time a test run starts it installs the module and all their dependencies, when may be it is not required when the database already exists. This is takes a lot of time and makes unit testing tedious.

I tried commenting line 51 (self.openerp.install_module(self.config['module'])) and the speed improvement is huge!

I propose two possible solutions that:
- Be more smart installing the module only when it is necessary (I am not really sure this is really possible).
- Add an environment variable or paramter to disable installation of the module showing a warning so developer knows it is disabled.

**Comment by ecarreras** [comment]
Thank you @rchamorro, I'll provide a fix for it
