### ISSUE TITLE
Geneate Junit XML results

### ISSUE THREAD

**Issue by ecarreras** [gisce/destral#96]
Circle CI supports [tests metadata](https://circleci.com/docs/2.0/collect-test-data/#nav-button) which inform the failed tests, slower tests, etc.

This metada uses [Junit XML format](https://www.ibm.com/support/knowledgecenter/en/SSQ2R2_9.5.0/com.ibm.rsar.analysis.codereview.cobol.doc/topics/cac_useresults_junit.html)

We have two options:
- Use [python-junit-xml](https://github.com/kyrus/python-junit-xml) to generate the XML and use the API of Unittest to create the objects
- Integrate with library [py.test](https://pytest.org) which already [supports Junit XML files](https://docs.pytest.org/en/latest/usage.html#creating-junitxml-format-files)

**Comment by jaumef** [comment]
## PyTest
I've been trying to integrate py.test on our tests, but "`loadmodules`" and TestSuite's running are not compatible with pytest. 

- Pytest uses it's command line method and a hooks system to run the test, so the openerp service environment can't be passed throght args.
- Pytests can run unittest class-based tests but from a specified directory and without "extra-args".

→We can run tests with pytest adding fixtures and selecting by-module fixtures on pytest run, but it's kind of hard to integrate on our testing methods.
- We may add the fixtures to each unittest class
- We may add init fixtures to init the openerp service, install the modules ...
- We may setup the openerp service in a fixture (not in destral)
- We may add distinct marks on each test, so we can keep the one-test-run (`-t` functionality)

----

I'd proceed to get more info on [python-junit-xml](https://github.com/kyrus/python-junit-xml) to integrate with unittest API.

**Comment by jaumef** [comment]
## Python-junit-xml

It turned out to be pretty simple with Unittest API, even if it carries a bit of work it just modifies this repo's internal API.

I'm proceeding with this method.
